# Generated by Django 4.1.2 on 2022-10-06 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('icon', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'developer',
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(blank=True, max_length=200, null=True)),
                ('developer', models.ForeignKey(db_column='developer', on_delete=django.db.models.deletion.DO_NOTHING, to='ExTime.developer')),
            ],
            options={
                'db_table': 'games',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=50)),
                ('review_text', models.TextField(db_column='review text', max_length=1000)),
                ('rating', models.IntegerField()),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='Servicetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
            ],
            options={
                'db_table': 'servicetype',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('is_seller', models.IntegerField(db_column='is-seller')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Servicescreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(max_length=500)),
                ('serviceid', models.ForeignKey(db_column='serviceid', on_delete=django.db.models.deletion.DO_NOTHING, to='ExTime.service')),
            ],
            options={
                'db_table': 'servicescreenshot',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='author',
            field=models.ForeignKey(db_column='author', on_delete=django.db.models.deletion.DO_NOTHING, to='ExTime.user'),
        ),
        migrations.AddField(
            model_name='service',
            name='gameid',
            field=models.ForeignKey(db_column='gameid', on_delete=django.db.models.deletion.DO_NOTHING, to='ExTime.games'),
        ),
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.DO_NOTHING, to='ExTime.servicetype'),
        ),
        migrations.CreateModel(
            name='Reviewscreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(max_length=500)),
                ('reviewid', models.ForeignKey(db_column='reviewid', on_delete=django.db.models.deletion.DO_NOTHING, to='ExTime.reviews')),
            ],
            options={
                'db_table': 'reviewscreenshot',
            },
        ),
        migrations.AddField(
            model_name='reviews',
            name='serviceid',
            field=models.ForeignKey(db_column='serviceid', on_delete=django.db.models.deletion.DO_NOTHING, to='ExTime.service'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='userid',
            field=models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.DO_NOTHING, to='ExTime.user'),
        ),
    ]
