# Generated by Django 4.1.2 on 2022-10-08 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExTime', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developer',
            old_name='name',
            new_name='dev_name',
        ),
    ]
