# Generated by Django 4.1.2 on 2022-10-08 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExTime', '0002_rename_name_developer_dev_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='developer',
            new_name='developer_id',
        ),
        migrations.RenameField(
            model_name='games',
            old_name='name',
            new_name='game_name',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='userid',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='reviewscreenshot',
            old_name='screen',
            new_name='pic_name',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='service_name',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='type',
            new_name='type_id',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='author',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='servicescreenshot',
            old_name='screen',
            new_name='pic_name',
        ),
        migrations.RenameField(
            model_name='servicetype',
            old_name='name',
            new_name='typename',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='user_name',
        ),
    ]
